config/routes.rb
Rails.application.routes.draw do
  get 'bottles/:number_of_bottles' => 'bottles#bottles', as: 'bottles'
  get 'take/:number_of_bottles' => 'bottles#take', as: 'take'
  get 'go/to/store' => 'bottles#store', as: 'store'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  def bottles
    @number_of_bottles = params[:number_of_bottles].to_i
  end

  def take
    @one_less = params[:number_of_bottles].to_i - 1
  end

  def store
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bottles/bottles.html.erb
<% if @number_of_bottles > 0 %>
  <h1><%= pluralize(@number_of_bottles, 'bottle') %> of beer on the wall,</h1>
  <h2><%= pluralize(@number_of_bottles, 'bottle') %> of beer</h2>

  <% @number_of_bottles.times do |number| %>
    <%= image_tag('bottles_of_beer.gif') %>
    <% if number % 10 == 9 %>
      <br>
    <% end %>
  <% end %>

  <%= link_to 'Take one down...', take_path(@number_of_bottles) %>
<% else %>
  <h1>No more bottles of beer on the wall,</h1>
  <h2>No more bottles of beer</h2>

  <%= link_to 'Go to the store...', store_path %>
<% end %>

app/views/bottles/store.html.erb
<h1>Go to the store,</h1>

<%= link_to 'Buy some more...', bottles_path(99) %>

app/views/bottles/take.html.erb
<h1>Take one down,</h1>

<%= image_tag('homer_beer.gif') %>

<%= link_to 'Pass it around...', bottles_path(@one_less) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineBottles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>